baseurl         = "//varezers.org"
title           = "Varezers"
theme           = "Diogenes"
canonifyurls    = true
pygmentsStyle   = "monokai"
rssLimit        = 50
enableEmoji     = true
enableRSS		= true

[params]
    description = "Reflections on art, adventures, philosophy, life and everything..."
    welcome_header = "Kaspars. > Explorer, problem solver, and skill collector."
[permalinks]
    post         = ":slug"
    propaganda   = ":slug"
[sitemap]
    priority    = 0.5
    filename    = "sitemap.xml"
[markup]
  [markup.goldmark.extensions]
    definitionList = true
    table = true
    typographer = false
  [markup.goldmark.renderer]
    unsafe = true

[outputs]
    home = ["HTML","RSS"]

[mediaTypes]
    [mediaTypes."application/rss"]
        suffixes        = ["xml"]

[outputFormats]
    [outputFormats.RSS]
        mediatype       = "application/rss"
        baseName        = "feed"

[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        disable = true
    [privacy.instagram]
        disable = true
    [privacy.x]
        disable = true
    [privacy.vimeo]
        disable = true
    [privacy.youtube]
        disable = true
